spring.application.name=backend

# Default to dev profile if not specified
spring.profiles.active=dev

# Flyway Configuration (Common to all profiles)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
